"""Add selling_price to stocks

Revision ID: 0246b25a34b2
Revises: 6fa373684f00
Create Date: 2026-02-02 14:42:40.413704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0246b25a34b2'
down_revision = '6fa373684f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))
        batch_op.alter_column('unit_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
