"""Add KRA compliance fields to sale

Revision ID: 3bc737585423
Revises: 88d21448394c
Create Date: 2026-03-02 18:37:18.156063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc737585423'
down_revision = '88d21448394c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kra_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kra_icn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kra_qr_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kra_control_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kra_response_payload', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('kra_response_payload')
        batch_op.drop_column('kra_control_number')
        batch_op.drop_column('kra_qr_code')
        batch_op.drop_column('kra_icn')
        batch_op.drop_column('kra_status')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
