"""Add branch and device models

Revision ID: 6bb06246df1f
Revises: c03f319c2d23
Create Date: 2026-03-02 12:54:25.040102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb06246df1f'
down_revision = 'c03f319c2d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kra_branch_code', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('device_serial', sa.String(length=120), nullable=False),
    sa.Column('device_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_branch_id'), ['branch_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        # batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_device_id'), ['device_id'], unique=False)
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'])
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('organization_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('organization_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_device_id'))
        batch_op.drop_index(batch_op.f('ix_sales_branch_id'))
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('device_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_branch_id'))

    op.drop_table('devices')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_organisation_id'))

    op.drop_table('branches')
    # ### end Alembic commands ###
