"""add cost snapshot

Revision ID: 792ab0d66f9b
Revises: 
Create Date: 2026-02-21 13:20:59.437279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792ab0d66f9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))

        op.execute("""
            UPDATE sale_items
            SET cost_price = stocks.unit_price
            FROM stocks
            WHERE sale_items.stock_id = stocks.id
            AND sale_items.cost_price IS NULL
        """)

    with op.batch_alter_table('sale_items') as batch_op:
        batch_op.alter_column(
            'cost_price',
            existing_type=sa.Numeric(10, 2),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
