"""Initial migration with KRA profiles

Revision ID: 88d21448394c
Revises: 
Create Date: 2026-03-02 14:39:11.621043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d21448394c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kra_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kra_pin', sa.String(length=20), nullable=False),
    sa.Column('etims_username', sa.String(length=100), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('certificate_path', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_branches_organisation_id'))
        batch_op.create_index(batch_op.f('ix_branches_organization_id'), ['organization_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('branches_organisation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('organisation_id')

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('organization_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('organization_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('branches_organisation_id_fkey'), 'organizations', ['organisation_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_branches_organization_id'))
        batch_op.create_index(batch_op.f('ix_branches_organisation_id'), ['organisation_id'], unique=False)
        batch_op.drop_column('organization_id')

    op.drop_table('kra_profiles')
    # ### end Alembic commands ###
