"""add subscription fields to organizations

Revision ID: c03f319c2d23
Revises: 792ab0d66f9b
Create Date: 2026-02-25 13:25:27.834821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f319c2d23'
down_revision = '792ab0d66f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('organization_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('trial_ends_at')

    # ### end Alembic commands ###
